/* The Alums — Oregon ProDucks pipeline
   Seed data for v1. In production this comes from NFL APIs + a CMS. */

window.FLOCK = window.FLOCK || {};

FLOCK.meta = {
  brand: "The Alums",
  tagline: "Every Duck. Every Sunday.",
  school: "Oregon Ducks",
  season: 2026,
  week: 1,
  lastUpdated: "September 15, 2026",
  activeCount: 36,
  teamsRepresented: 24,
  firstRoundStreak: 7
};

FLOCK.players = [
  {
    id: "herbert",
    name: "Justin Herbert",
    pos: "QB",
    team: "LAC",
    teamName: "Los Angeles Chargers",
    league: "NFL",
    years: 7,
    draft: "2020 · R1 #6",
    yearsAtOregon: "2016–2019",
    status: "Starter",
    jersey: 10,
    featured: true,
    fantasyRelevant: true,
    bio: "The face of the modern Oregon pipeline. Herbert left Eugene as a dual-threat Heisman finalist and has become one of the NFL's most complete quarterbacks — a 6-foot-6 processor with a cannon and surprising mobility.",
    week1: { result: "L 14–26 vs ARI", pass: "17/27, 209 yds, 1 TD, 1 INT", rush: "5–29", ppr: 13.3, note: "Middling afternoon in a Chargers upset loss." },
    season: { passYds: 209, passTD: 1, int: 1, rushYds: 29, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 13.3, proj: 19.0, adp: "QB8", grade: "A-" }
  },
  {
    id: "nix",
    name: "Bo Nix",
    pos: "QB",
    team: "DEN",
    teamName: "Denver Broncos",
    league: "NFL",
    years: 3,
    draft: "2024 · R1 #12",
    yearsAtOregon: "2022–2023",
    status: "Starter",
    jersey: 10,
    featured: true,
    fantasyRelevant: true,
    bio: "Transferred from Auburn and remade himself in Eugene. Nix led Oregon to the College Football Playoff and has settled in as Denver's starter — a high-volume passer with enough legs to stay fantasy-relevant.",
    week1: { result: "L 10–31 vs KC", pass: "17/28, 176 yds, 1 TD, 2 INT", rush: "3–18", ppr: 8.8, note: "Tough road opener against Kansas City." },
    season: { passYds: 176, passTD: 1, int: 2, rushYds: 18, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 8.8, proj: 16.1, adp: "QB14", grade: "C-" }
  },
  {
    id: "mariota",
    name: "Marcus Mariota",
    pos: "QB",
    team: "WAS",
    teamName: "Washington Commanders",
    league: "NFL",
    years: 12,
    draft: "2015 · R1 #2",
    yearsAtOregon: "2011–2014",
    status: "Backup",
    jersey: 8,
    featured: false,
    fantasyRelevant: false,
    bio: "Heisman winner, program icon, and still one of the most trusted backup quarterbacks in the league. Mariota remains the elder statesman of the Oregon QB tree.",
    week1: { result: "Did not play", pass: "—", rush: "—", ppr: 0, note: "Emergency QB behind Jayden Daniels." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "UDFA", grade: "Sit" }
  },
  {
    id: "irving",
    name: "Bucky Irving",
    pos: "RB",
    team: "TB",
    teamName: "Tampa Bay Buccaneers",
    league: "NFL",
    years: 3,
    draft: "2024 · R4 #125",
    yearsAtOregon: "2022–2023",
    status: "Starter",
    jersey: 7,
    featured: true,
    fantasyRelevant: true,
    bio: "A compact, decisive runner who turned a mid-round draft slot into a featured role in Tampa. Irving is the most valuable Oregon skill player in fantasy formats right now.",
    week1: { result: "L @ CIN", pass: "—", rush: "~16 touches, receiving TD", ppr: 12.5, note: "Primary back; mixed box with a receiving score." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 37, rushTD: 0, rec: 4, recYds: 8, recTD: 1, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 12.5, proj: 13.5, adp: "RB22", grade: "B" }
  },
  {
    id: "james",
    name: "Jordan James",
    pos: "RB",
    team: "SF",
    teamName: "San Francisco 49ers",
    league: "NFL",
    years: 2,
    draft: "2025 · R5",
    yearsAtOregon: "2021–2024",
    status: "Rotation",
    jersey: 3,
    featured: false,
    fantasyRelevant: true,
    bio: "Power runner out of the Oregon backfield now in a crowded San Francisco room. Depth-chart climber with weekly dart-throw appeal if injuries hit.",
    week1: { result: "Limited snaps", pass: "—", rush: "Depth", ppr: 1.2, note: "Behind the 49ers' established committee." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 8, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 1.2, proj: 3.4, adp: "Waiver", grade: "Sit" }
  },
  {
    id: "franklin",
    name: "Troy Franklin",
    pos: "WR",
    team: "DEN",
    teamName: "Denver Broncos",
    league: "NFL",
    years: 3,
    draft: "2024 · R4 #102",
    yearsAtOregon: "2021–2023",
    status: "Rotation",
    jersey: 11,
    featured: true,
    fantasyRelevant: true,
    bio: "Deep threat who stretched the field for Nix in Eugene and is still hunting a consistent target share in Denver. Big-play profile, week-to-week volatility.",
    week1: { result: "L 10–31 vs KC", pass: "—", rush: "—", ppr: 4.1, note: "Quiet in a stalled Broncos passing game." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 2, recYds: 21, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 4.1, proj: 8.6, adp: "WR5/flex", grade: "C" }
  },
  {
    id: "tez",
    name: "Tez Johnson",
    pos: "WR",
    team: "TB",
    teamName: "Tampa Bay Buccaneers",
    league: "NFL",
    years: 2,
    draft: "2025 · UDFA / mid",
    yearsAtOregon: "2023–2024",
    status: "Rotation",
    jersey: 15,
    featured: false,
    fantasyRelevant: true,
    bio: "Shifty slot and return option. Flash plays and a highlight-reel celebration style — the kind of Duck who shows up on every Sunday slate even when the box score is modest.",
    week1: { result: "Special teams + offense", pass: "—", rush: "—", ppr: 3.8, note: "Mixed offensive/return snaps." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 2, recYds: 18, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 3.8, proj: 5.2, adp: "Waiver", grade: "Sit" }
  },
  {
    id: "benson",
    name: "Malik Benson",
    pos: "WR",
    team: "LV",
    teamName: "Las Vegas Raiders",
    league: "NFL",
    years: 1,
    draft: "2026 · R6 #195",
    yearsAtOregon: "2025",
    status: "Rookie",
    jersey: 19,
    featured: false,
    fantasyRelevant: false,
    bio: "Transfer-portal receiver who led Oregon in receiving yards in 2025. Developmental piece in Las Vegas after a sixth-round selection.",
    week1: { result: "Limited", pass: "—", rush: "—", ppr: 0.0, note: "Rookie getting his feet wet." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 1.5, adp: "UDFA", grade: "Sit" }
  },
  {
    id: "sadiq",
    name: "Kenyon Sadiq",
    pos: "TE",
    team: "NYJ",
    teamName: "New York Jets",
    league: "NFL",
    years: 1,
    draft: "2026 · R1 #16",
    yearsAtOregon: "2023–2025",
    status: "Starter",
    jersey: 16,
    featured: true,
    fantasyRelevant: true,
    bio: "First-round tight end who announced himself immediately — a rushing touchdown in the first five minutes of his NFL career. Big Ten TE of the Year in 2025. The rookie to watch.",
    week1: { result: "W 23–10 @ TEN", pass: "3 rec, 21 yds", rush: "1–3, 1 TD", ppr: 11.4, note: "Rushing TD on his first NFL series." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 3, rushTD: 1, rec: 3, recYds: 21, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 11.4, proj: 8.2, adp: "TE streamer", grade: "B+" }
  },
  {
    id: "juwan",
    name: "Juwan Johnson",
    pos: "TE",
    team: "NO",
    teamName: "New Orleans Saints",
    league: "NFL",
    years: 7,
    draft: "2020 · UDFA",
    yearsAtOregon: "2015–2018",
    status: "Starter",
    jersey: 83,
    featured: false,
    fantasyRelevant: true,
    bio: "Converted receiver who became a Saints tight end staple. Reliable red-zone target and one of the longer-tenured Ducks still producing on offense.",
    week1: { result: "Starter snaps", pass: "—", rush: "—", ppr: 6.4, note: "In the Saints two-TE look." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 3, recYds: 34, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 6.4, proj: 7.8, adp: "TE2", grade: "C+" }
  },
  {
    id: "ferguson",
    name: "Terrance Ferguson",
    pos: "TE",
    team: "LAR",
    teamName: "Los Angeles Rams",
    league: "NFL",
    years: 2,
    draft: "2025 · R2 #46",
    yearsAtOregon: "2021–2024",
    status: "Rotation",
    jersey: 18,
    featured: false,
    fantasyRelevant: true,
    bio: "Athletic mismatch tight end drafted to grow in Sean McVay's offense. Year-two leap candidate.",
    week1: { result: "Rotational", pass: "—", rush: "—", ppr: 2.6, note: "Mixed into 12 personnel." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 1, recYds: 16, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 2.6, proj: 4.1, adp: "Waiver", grade: "Sit" }
  },
  {
    id: "mundt",
    name: "Johnny Mundt",
    pos: "TE",
    team: "PHI",
    teamName: "Philadelphia Eagles",
    league: "NFL",
    years: 9,
    draft: "2017 · UDFA",
    yearsAtOregon: "2013–2016",
    status: "Depth",
    jersey: 82,
    featured: false,
    fantasyRelevant: false,
    bio: "Blocking specialist and special-teams veteran. One of the quieter, longer Oregon careers in the league.",
    week1: { result: "ST / 12 personnel", pass: "—", rush: "—", ppr: 0, note: "Blocking role." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0.4, adp: "—", grade: "Sit" }
  },
  {
    id: "sewell",
    name: "Penei Sewell",
    pos: "OT",
    team: "DET",
    teamName: "Detroit Lions",
    league: "NFL",
    years: 6,
    draft: "2021 · R1 #7",
    yearsAtOregon: "2018–2020",
    status: "Starter",
    jersey: 58,
    featured: true,
    fantasyRelevant: false,
    bio: "Consensus top-three tackle in football. Left-side anchor in Detroit and the gold standard for Oregon offensive linemen. All-Pro caliber every season.",
    week1: { result: "Started at LT", pass: "—", rush: "—", ppr: 0, note: "Full-game starter. No flags of note." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "IDP only", grade: "—" }
  },
  {
    id: "jpj",
    name: "Jackson Powers-Johnson",
    pos: "OL",
    team: "LV",
    teamName: "Las Vegas Raiders",
    league: "NFL",
    years: 3,
    draft: "2024 · R2 #44",
    yearsAtOregon: "2021–2023",
    status: "Starter",
    jersey: 58,
    featured: true,
    fantasyRelevant: false,
    bio: "Rimington-level interior lineman who can play guard or center. Already a Raiders building block on the interior.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 0, note: "Interior starter." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "bass",
    name: "T.J. Bass",
    pos: "OL",
    team: "DAL",
    teamName: "Dallas Cowboys",
    league: "NFL",
    years: 4,
    draft: "2023 · UDFA",
    yearsAtOregon: "2018–2022",
    status: "Rotation",
    jersey: 66,
    featured: false,
    fantasyRelevant: false,
    bio: "Undrafted success story. Versatile interior/tackle depth who has carved out a real NFL role in Dallas.",
    week1: { result: "ST snaps", pass: "—", rush: "—", ppr: 0, note: "Four special-teams snaps reported." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "forsyth",
    name: "Alex Forsyth",
    pos: "OL",
    team: "DEN",
    teamName: "Denver Broncos",
    league: "NFL",
    years: 4,
    draft: "2023 · R7",
    yearsAtOregon: "2018–2022",
    status: "Rotation",
    jersey: 54,
    featured: false,
    fantasyRelevant: false,
    bio: "Center/guard who stayed in the same city as Nix. Reliable depth with starting experience.",
    week1: { result: "Active", pass: "—", rush: "—", ppr: 0, note: "Interior depth." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "conerly",
    name: "Josh Conerly Jr.",
    pos: "OL",
    team: "WAS",
    teamName: "Washington Commanders",
    league: "NFL",
    years: 2,
    draft: "2025 · R1",
    yearsAtOregon: "2022–2024",
    status: "Starter",
    jersey: 76,
    featured: true,
    fantasyRelevant: false,
    bio: "First-round tackle out of the 2025 class. Immediate starter in Washington's rebuilt line — the next Sewell-track Duck.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 0, note: "Full-game starter at tackle." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "pregnon",
    name: "Emmanuel Pregnon",
    pos: "OL",
    team: "JAC",
    teamName: "Jacksonville Jaguars",
    league: "NFL",
    years: 1,
    draft: "2026 · R3 #88",
    yearsAtOregon: "2024–2025",
    status: "Rookie",
    jersey: 75,
    featured: false,
    fantasyRelevant: false,
    bio: "Third-round guard from the 2026 draft. Physical interior prospect who made Jacksonville's 53 as a rookie.",
    week1: { result: "Active", pass: "—", rush: "—", ppr: 0, note: "Rookie interior snaps." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "cornelius",
    name: "Ajani Cornelius",
    pos: "OL",
    team: "DAL",
    teamName: "Dallas Cowboys",
    league: "NFL",
    years: 2,
    draft: "2025 · R6",
    yearsAtOregon: "2023–2024",
    status: "Depth",
    jersey: 65,
    featured: false,
    fantasyRelevant: false,
    bio: "Tackle/guard swing who followed the Oregon OL factory into Dallas.",
    week1: { result: "Inactive / depth", pass: "—", rush: "—", ppr: 0, note: "Depth chart." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "harkey",
    name: "Alex Harkey",
    pos: "OL",
    team: "LAC",
    teamName: "Los Angeles Chargers",
    league: "NFL",
    years: 1,
    draft: "2026 · R6 #206",
    yearsAtOregon: "2023–2025",
    status: "Rookie",
    jersey: 68,
    featured: false,
    fantasyRelevant: false,
    bio: "Sixth-round interior lineman joining Herbert in Los Angeles.",
    week1: { result: "Active", pass: "—", rush: "—", ppr: 0, note: "Rookie OL." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "—", grade: "—" }
  },
  {
    id: "buckner",
    name: "DeForest Buckner",
    pos: "DL",
    team: "IND",
    teamName: "Indianapolis Colts",
    league: "NFL",
    years: 11,
    draft: "2016 · R1 #7",
    yearsAtOregon: "2012–2015",
    status: "Starter",
    jersey: 99,
    featured: true,
    fantasyRelevant: true,
    bio: "Still a wrecking-ball three-technique more than a decade in. The senior voice of the Duck defensive line tree.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 8.5, note: "Interior disruption, IDP staple." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 5, sacks: 0.5 },
    fantasy: { week1PPR: 8.5, proj: 9.2, adp: "IDP DL1", grade: "Start" }
  },
  {
    id: "armstead",
    name: "Arik Armstead",
    pos: "DL",
    team: "JAC",
    teamName: "Jacksonville Jaguars",
    league: "NFL",
    years: 12,
    draft: "2015 · R1 #17",
    yearsAtOregon: "2012–2014",
    status: "Starter",
    jersey: 91,
    featured: true,
    fantasyRelevant: true,
    bio: "Twelve-year veteran still starting on the interior. Sacramento-to-Eugene-to-the-league path that defined a generation of Duck linemen.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 6.0, note: "Veteran snaps." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 3, sacks: 0 },
    fantasy: { week1PPR: 6.0, proj: 7.1, adp: "IDP", grade: "Flex" }
  },
  {
    id: "thibodeaux",
    name: "Kayvon Thibodeaux",
    pos: "OLB",
    team: "NYG",
    teamName: "New York Giants",
    league: "NFL",
    years: 5,
    draft: "2022 · R1 #5",
    yearsAtOregon: "2019–2021",
    status: "Starter",
    jersey: 5,
    featured: true,
    fantasyRelevant: true,
    bio: "Edge rusher with first-round pedigree and a flair for the moment. Still hunting a true breakout year in New York.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 7.5, note: "Edge snaps, pressure without a sack." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 4, sacks: 0 },
    fantasy: { week1PPR: 7.5, proj: 10.4, adp: "IDP EDGE", grade: "Start" }
  },
  {
    id: "harmon",
    name: "Derrick Harmon",
    pos: "DL",
    team: "PIT",
    teamName: "Pittsburgh Steelers",
    league: "NFL",
    years: 2,
    draft: "2025 · R1 #22",
    yearsAtOregon: "2023–2024",
    status: "Starter",
    jersey: 99,
    featured: true,
    fantasyRelevant: true,
    bio: "First-round interior defender now in Pittsburgh's always-physical front. Year-two starter with IDP upside.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 5.5, note: "Steelers rotation." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 3, sacks: 0 },
    fantasy: { week1PPR: 5.5, proj: 8.0, adp: "IDP", grade: "Flex" }
  },
  {
    id: "dorlus",
    name: "Brandon Dorlus",
    pos: "DL",
    team: "ATL",
    teamName: "Atlanta Falcons",
    league: "NFL",
    years: 3,
    draft: "2024 · R4",
    yearsAtOregon: "2019–2023",
    status: "Rotation",
    jersey: 92,
    featured: false,
    fantasyRelevant: false,
    bio: "Long-armed interior/edge hybrid. Rotational piece in Atlanta.",
    week1: { result: "Rotation", pass: "—", rush: "—", ppr: 3.0, note: "Sub-package snaps." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 2, sacks: 0 },
    fantasy: { week1PPR: 3.0, proj: 4.0, adp: "—", grade: "Sit" }
  },
  {
    id: "caldwell",
    name: "Jamaree Caldwell",
    pos: "DL",
    team: "LAC",
    teamName: "Los Angeles Chargers",
    league: "NFL",
    years: 2,
    draft: "2025 · R3",
    yearsAtOregon: "2024",
    status: "Rotation",
    jersey: 90,
    featured: false,
    fantasyRelevant: false,
    bio: "Transfer nose who joined Herbert's Chargers after one year in Eugene.",
    week1: { result: "Rotation", pass: "—", rush: "—", ppr: 2.5, note: "Interior rotation." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 2, sacks: 0 },
    fantasy: { week1PPR: 2.5, proj: 3.5, adp: "—", grade: "Sit" }
  },
  {
    id: "burch",
    name: "Jordan Burch",
    pos: "OLB",
    team: "ARI",
    teamName: "Arizona Cardinals",
    league: "NFL",
    years: 2,
    draft: "2025 · R3",
    yearsAtOregon: "2023–2024",
    status: "Rotation",
    jersey: 3,
    featured: false,
    fantasyRelevant: false,
    bio: "Long edge who transferred in and left as a mid-round pick. Developing pass-rush piece in Arizona.",
    week1: { result: "Rotation", pass: "—", rush: "—", ppr: 2.0, note: "Sub-package edge." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 1, sacks: 0 },
    fantasy: { week1PPR: 2.0, proj: 3.2, adp: "—", grade: "Sit" }
  },
  {
    id: "dye",
    name: "Troy Dye",
    pos: "LB",
    team: "LAC",
    teamName: "Los Angeles Chargers",
    league: "NFL",
    years: 7,
    draft: "2020 · R4",
    yearsAtOregon: "2016–2019",
    status: "Starter",
    jersey: 43,
    featured: false,
    fantasyRelevant: true,
    bio: "Tackling machine from the Herbert-era defense. Special-teams ace who has grown into a regular defensive role.",
    week1: { result: "Started / ST", pass: "—", rush: "—", ppr: 9.0, note: "Marquee tackling day flagged in Oregon's ProDucks recap." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 8, sacks: 0 },
    fantasy: { week1PPR: 9.0, proj: 7.5, adp: "IDP LB", grade: "Start" }
  },
  {
    id: "bassa",
    name: "Jeffrey Bassa",
    pos: "LB",
    team: "KC",
    teamName: "Kansas City Chiefs",
    league: "NFL",
    years: 2,
    draft: "2025 · R5",
    yearsAtOregon: "2021–2024",
    status: "Rotation",
    jersey: 31,
    featured: false,
    fantasyRelevant: false,
    bio: "Physical linebacker now in Kansas City's always-loaded front seven.",
    week1: { result: "ST + defense", pass: "—", rush: "—", ppr: 3.5, note: "Special teams and sub-package." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 3, sacks: 0 },
    fantasy: { week1PPR: 3.5, proj: 4.0, adp: "—", grade: "Sit" }
  },
  {
    id: "boettcher",
    name: "Bryce Boettcher",
    pos: "LB",
    team: "IND",
    teamName: "Indianapolis Colts",
    league: "NFL",
    years: 1,
    draft: "2026 · R4 #135",
    yearsAtOregon: "2021–2025",
    status: "Rookie",
    jersey: 50,
    featured: true,
    fantasyRelevant: true,
    bio: "Local product and tackling machine. Seven tackles in his NFL debut — instant impact as a rookie linebacker in Indianapolis.",
    week1: { result: "L 23–41 vs BAL", pass: "—", rush: "—", ppr: 10.5, note: "Seven tackles in debut." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 7, sacks: 0 },
    fantasy: { week1PPR: 10.5, proj: 6.8, adp: "IDP sleeper", grade: "Start" }
  },
  {
    id: "gonzalez",
    name: "Christian Gonzalez",
    pos: "CB",
    team: "NE",
    teamName: "New England Patriots",
    league: "NFL",
    years: 4,
    draft: "2023 · R1 #17",
    yearsAtOregon: "2021–2022",
    status: "Starter",
    jersey: 0,
    featured: true,
    fantasyRelevant: true,
    bio: "Cover corner on a Super Bowl trajectory. One of the highest-paid-corner conversations in football after anchoring New England's defense.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 6.0, note: "Locked the boundary." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 4, sacks: 0 },
    fantasy: { week1PPR: 6.0, proj: 7.8, adp: "IDP DB", grade: "Start" }
  },
  {
    id: "holland",
    name: "Jevon Holland",
    pos: "S",
    team: "NYG",
    teamName: "New York Giants",
    league: "NFL",
    years: 6,
    draft: "2021 · R2",
    yearsAtOregon: "2018–2020",
    status: "Starter",
    jersey: 8,
    featured: true,
    fantasyRelevant: true,
    bio: "Rangy free safety with ball skills. Now paired with Thibodeaux in New York — an all-Oregon defensive backfield look on some snaps.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 11.0, note: "Marquee performance in Oregon's Week 1 recap." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 8, sacks: 0 },
    fantasy: { week1PPR: 11.0, proj: 9.5, adp: "IDP S", grade: "Start" }
  },
  {
    id: "lenoir",
    name: "Deommodore Lenoir",
    pos: "CB",
    team: "SF",
    teamName: "San Francisco 49ers",
    league: "NFL",
    years: 6,
    draft: "2021 · R5",
    yearsAtOregon: "2017–2020",
    status: "Starter",
    jersey: 2,
    featured: true,
    fantasyRelevant: true,
    bio: "Fifth-round steal who became a full-time starter in San Francisco's secondary. Physical, smart, and rarely off the field.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 7.0, note: "Boundary starter." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 5, sacks: 0 },
    fantasy: { week1PPR: 7.0, proj: 7.2, adp: "IDP", grade: "Start" }
  },
  {
    id: "thieneman",
    name: "Dillon Thieneman",
    pos: "S",
    team: "CHI",
    teamName: "Chicago Bears",
    league: "NFL",
    years: 1,
    draft: "2026 · R1 #25",
    yearsAtOregon: "2025",
    status: "Starter",
    jersey: 31,
    featured: true,
    fantasyRelevant: true,
    bio: "First-round safety after one year in Eugene (via Purdue). Earned a game ball in his NFL debut — the defensive headline of Week 1 for the Flock.",
    week1: { result: "Started · game ball", pass: "—", rush: "—", ppr: 14.0, note: "Game ball in debut. Best Duck defensive day of Week 1." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 9, sacks: 0 },
    fantasy: { week1PPR: 14.0, proj: 8.5, adp: "IDP sleeper", grade: "Start" }
  },
  {
    id: "canady",
    name: "Jadon Canady",
    pos: "DB",
    team: "KC",
    teamName: "Kansas City Chiefs",
    league: "NFL",
    years: 1,
    draft: "2026 · R4 #109",
    yearsAtOregon: "2025",
    status: "Rookie",
    jersey: 29,
    featured: false,
    fantasyRelevant: false,
    bio: "Ole Miss transfer who started 13 games for Oregon in 2025. Fourth-round pick into Kansas City's secondary.",
    week1: { result: "Active", pass: "—", rush: "—", ppr: 1.5, note: "Rookie DB snaps." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 1, sacks: 0 },
    fantasy: { week1PPR: 1.5, proj: 2.0, adp: "—", grade: "Sit" }
  },
  {
    id: "williams",
    name: "Evan Williams",
    pos: "S",
    team: "GB",
    teamName: "Green Bay Packers",
    league: "NFL",
    years: 3,
    draft: "2024 · R4",
    yearsAtOregon: "2022–2023",
    status: "Starter",
    jersey: 33,
    featured: false,
    fantasyRelevant: true,
    bio: "Physical safety who earned a starting job in Green Bay. Another mid-round Duck who outplayed his draft slot.",
    week1: { result: "Started", pass: "—", rush: "—", ppr: 8.0, note: "Marquee Week 1 mention from Oregon Athletics." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 6, sacks: 0 },
    fantasy: { week1PPR: 8.0, proj: 7.4, adp: "IDP", grade: "Flex" }
  },
  {
    id: "adams",
    name: "Vernon Adams Jr.",
    pos: "QB",
    team: "BC",
    teamName: "BC Lions",
    league: "CFL",
    years: 10,
    draft: "CFL free agent",
    yearsAtOregon: "2013–2015",
    status: "CFL",
    jersey: 8,
    featured: false,
    fantasyRelevant: false,
    bio: "Oregon-to-CFL quarterback. Separate board from the NFL Sunday slate.",
    week1: { result: "CFL slate", pass: "—", rush: "—", ppr: 0, note: "Tracked on the North of the Border chip." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "CFL", grade: "—" }
  },
  {
    id: "addison",
    name: "Bralon Addison",
    pos: "WR",
    team: "SSK",
    teamName: "Saskatchewan Roughriders",
    league: "CFL",
    years: 8,
    draft: "CFL",
    yearsAtOregon: "2013–2015",
    status: "CFL",
    jersey: 0,
    featured: false,
    fantasyRelevant: false,
    bio: "Former Duck receiver in the CFL. Kept on a separate filter so the NFL board stays clean.",
    week1: { result: "CFL slate", pass: "—", rush: "—", ppr: 0, note: "North of the Border." },
    season: { passYds: 0, passTD: 0, int: 0, rushYds: 0, rushTD: 0, rec: 0, recYds: 0, recTD: 0, tackles: 0, sacks: 0 },
    fantasy: { week1PPR: 0, proj: 0, adp: "CFL", grade: "—" }
  },

];

FLOCK.news = [
  {
    id: "n1",
    tag: "Week 1",
    featured: true,
    title: "Sadiq scores on his first NFL series. Thieneman takes a game ball.",
    dek: "Two first-round Ducks from the 2026 draft announced themselves on Sunday. The Jets tight end punched in a rushing score before the game was five minutes old.",
    time: "Sep 15, 2026",
    author: "The Alums Desk",
    playerIds: ["sadiq", "thieneman"]
  },
  {
    id: "n2",
    tag: "Quarterbacks",
    featured: true,
    title: "Herbert's Chargers drop a stunner. Nix walks into a Kansas City buzzsaw.",
    dek: "The two Oregon starters on the slate both lost. Herbert went 17-of-27 for 209 and a score; Nix was sacked into a 10–31 hole in Denver.",
    time: "Sep 15, 2026",
    author: "The Alums Desk",
    playerIds: ["herbert", "nix"]
  },
  {
    id: "n3",
    tag: "Rookies",
    featured: false,
    title: "Boettcher posts seven tackles in his Colts debut.",
    dek: "The fourth-round linebacker looked like a three-year starter on day one. Indianapolis has a Duck in the middle of the defense.",
    time: "Sep 14, 2026",
    author: "The Alums Desk",
    playerIds: ["boettcher"]
  },
  {
    id: "n4",
    tag: "Fantasy",
    featured: false,
    title: "Bucky Irving is the desk's RB1 until further notice.",
    dek: "A receiving touchdown and the lead back role in Tampa keep Irving in every starting lineup. Franklin and Sadiq are the streaming questions.",
    time: "Sep 15, 2026",
    author: "The Alums Desk",
    playerIds: ["irving", "sadiq", "franklin"]
  },
  {
    id: "n5",
    tag: "Pipeline",
    featured: false,
    title: "36 Ducks on 53-man rosters. Oregon sits 8th nationally.",
    dek: "Only the usual blue bloods — Ohio State, Alabama, Georgia, LSU, Notre Dame, Texas, Michigan — have more active alumni. Florida is tied.",
    time: "Sep 6, 2026",
    author: "The Alums Desk",
    playerIds: []
  },
  {
    id: "n6",
    tag: "O-Line",
    featured: false,
    title: "The factory is still open: Sewell, Conerly, Powers-Johnson start Week 1.",
    dek: "Three Oregon tackles/interior linemen opened as Week 1 starters. Pregnon and Harkey made the 53 as rookies.",
    time: "Sep 10, 2026",
    author: "The Alums Desk",
    playerIds: ["sewell", "conerly", "jpj"]
  },
  {
    id: "n7",
    tag: "Secondary",
    featured: false,
    title: "Gonzalez, Lenoir, Holland, Williams — the Duck secondary tree is blooming.",
    dek: "Four Oregon defensive backs opened as starters. Add Thieneman and the 2026 class and the pipeline is a DB factory now, too.",
    time: "Sep 12, 2026",
    author: "The Alums Desk",
    playerIds: ["gonzalez", "lenoir", "holland", "williams", "thieneman"]
  },
  {
    id: "n8",
    tag: "Injury",
    featured: false,
    title: "Dillon Gabriel opens the year on IR in Cleveland.",
    dek: "The former Duck quarterback will not be available for the Browns' early slate. Mariota remains the healthy veteran backup in Washington.",
    time: "Sep 1, 2026",
    author: "The Alums Desk",
    playerIds: ["mariota"]
  }
];

FLOCK.positions = ["All", "QB", "RB", "WR", "TE", "OL", "OT", "DL", "OLB", "LB", "CB", "S", "DB"];

FLOCK.prospects = [
  {
    id: "moore",
    name: "Dante Moore",
    pos: "QB",
    class: 2027,
    status: "Watch list",
    ht: "6-3",
    wt: "215",
    forty: "—",
    shuttle: "—",
    vert: "—",
    broad: "—",
    bench: "—",
    note: "Projected first-round quarterback. Combine numbers land after the 2027 cycle."
  },
  {
    id: "jamari",
    name: "Jamari Johnson",
    pos: "TE",
    class: 2027,
    status: "Watch list",
    ht: "6-5",
    wt: "245",
    forty: "—",
    shuttle: "—",
    vert: "—",
    broad: "—",
    bench: "—",
    note: "Mismatch tight end. Pro day / combine board fills in spring 2027."
  },
  {
    id: "watch-ot",
    name: "Oregon OT board",
    pos: "OT",
    class: 2027,
    status: "Watch list",
    ht: "—",
    wt: "—",
    forty: "—",
    shuttle: "—",
    vert: "—",
    broad: "—",
    bench: "—",
    note: "Name locks after bowl season. Combine cells stay TBA until Indy."
  },
  {
    id: "watch-edge",
    name: "Oregon EDGE (TBA)",
    pos: "EDGE",
    class: 2027,
    status: "Measurables TBA",
    ht: "TBA", wt: "TBA", forty: "TBA", shuttle: "TBA", vert: "TBA", broad: "TBA", bench: "TBA",
    note: "Watch slot for a declared rusher."
  },
  {
    id: "watch-cb",
    name: "Oregon CB (TBA)",
    pos: "CB",
    class: 2027,
    status: "Measurables TBA",
    ht: "TBA", wt: "TBA", forty: "TBA", shuttle: "TBA", vert: "TBA", broad: "TBA", bench: "TBA",
    note: "Secondary pipeline. Official 40 after pro day."
  }
];

FLOCK.shopItems = [
  { id: "herbert-j", name: "Justin Herbert jersey", team: "Chargers", price: "From $149.99", href: "https://www.fanatics.com/nfl/los-angeles-chargers/justin-herbert/player-gear/o-2424+d-76997+z-89876-2370510473", art: "10" },
  { id: "nix-j", name: "Bo Nix jersey", team: "Broncos", price: "From $129.99", href: "https://www.fanatics.com/nfl/denver-broncos/bo-nix/player-gear/o-2422+d-76997+z-85732-2773512268", art: "10" },
  { id: "sewell-j", name: "Penei Sewell jersey", team: "Lions", price: "From $129.99", href: "https://www.fanatics.com/nfl/detroit-lions/penei-sewell/player-gear/o-2423+d-76997+z-90876-2160510373", art: "58" },
  { id: "irving-j", name: "Bucky Irving jersey", team: "Buccaneers", price: "From $129.99", href: "https://www.fanatics.com/nfl/tampa-bay-buccaneers", art: "7" }
];
